Repository Gamegoo-repo/Gamegoo-front-v2, pull requests merged in 2025-09, with the labels that each got.

#63 [Feat] 채팅 플로팅 버튼 추가
  CLAUDE.md
  components.json
  pnpm-lock.yaml
  src/app/App.tsx
  src/components/socket-test.tsx
  src/entities/chat/index.ts
  src/entities/chat/store.ts
  src/entities/chat/types.ts
  src/features/chat-notifications/index.ts
  src/features/chat-notifications/use-chat-notification.ts
  src/features/sign-in-user/index.ts
  src/features/sign-in-user/ui/login-button.tsx
  src/pages/__root.tsx
  src/pages/index.tsx
  src/pages/riot/callback.tsx
  src/pages/riot/index.tsx
  src/shared/api/socket/index.ts
  src/shared/api/socket/provider.tsx
  src/shared/icons/message.svg
  src/shared/lib/utils.ts
  src/shared/ui/badge/badge.tsx
  src/shared/ui/badge/index.ts
  src/shared/ui/logo/index.ts
  src/shared/ui/logo/logo-button.tsx
  src/widgets/auth/ui/auth-callback.tsx
  src/widgets/auth/ui/auth-section.tsx
  src/widgets/floating-chat-button/floating-chat-button.tsx
  src/widgets/floating-chat-button/index.ts
Labels: ✨ feature, 3️⃣ sub-task

#65 [Feat] 채팅 친구목록 추가
  biome.json
  components.json
  package.json
  pnpm-lock.yaml
  rsbuild.config.ts
  src/app/App.tsx
  src/app/styles/globals.css
  src/features/auth/api/auth-api.ts
  src/features/auth/index.ts
  src/features/chat-dialog-controller/index.ts
  src/features/chat-dialog-controller/model/store.ts
  src/features/draggable-dialog/index.ts
  src/features/draggable-dialog/model/store.ts
  src/features/draggable-dialog/model/types.ts
  src/features/draggable-dialog/model/use-drag.ts
  src/features/draggable-dialog/ui/draggable-dialog.tsx
  src/features/sign-in-user/api/login.ts
  src/index.tsx
  src/pages/__root.tsx
  src/pages/index.tsx
  src/shared/assets/icons/message.svg
  src/shared/assets/icons/search.svg
  src/shared/assets/icons/star.svg
  src/shared/assets/icons/star_violet.svg
  src/shared/lib/globals.css
  src/shared/providers/gamegoo-socket-provider.tsx
  src/shared/providers/index.ts
  src/shared/providers/tanstack-query-provider.tsx
  src/shared/ui/badge/index.ts
  src/test/components/socket-test.tsx
  src/widgets/chat-dialog/index.ts
  src/widgets/chat-dialog/ui/chat-content.tsx
  src/widgets/chat-dialog/ui/chat-dialog.tsx
  src/widgets/chat-dialog/ui/chat-tabs.tsx
  src/widgets/chat-dialog/ui/tab-contents/friend-item.tsx
  src/widgets/chat-dialog/ui/tab-contents/friend-list.tsx
  src/widgets/chat-dialog/ui/tab-contents/friend-section.tsx
  src/widgets/floating-chat-button/floating-chat-button.tsx
Labels: 📁 file, ✨ feature, 2️⃣ sub-issue

#64 [Feat] 회원가입 기능 구현
  biome.json
  package.json
  pnpm-lock.yaml
  rsbuild.config.ts
  src/features/auth/api/dto.ts
  src/features/auth/api/login.ts
  src/features/auth/api/mappers.ts
  src/features/auth/index.ts
  src/features/auth/model/types.ts
  src/features/auth/ui/login-button.tsx
  src/features/auth/ui/sign-up-button.tsx
  src/features/sign-in-user/index.ts
  src/pages/__root.tsx
  src/pages/join/terms.tsx
  src/pages/sign-up/terms.tsx
  src/shared/api/config.ts
  src/shared/assets/fonts/PretendardVariable.woff2
  src/shared/lib/@generated/routeTree.gen.ts
  src/shared/ui/checkbox/Checkbox.tsx
  src/widgets/auth/ui/auth-callback.tsx
  src/widgets/auth/ui/auth-section.tsx
  src/widgets/auth/ui/sign-up-section.tsx
Labels: 🔗 api, ✨ feature, 1️⃣ parent-issue
